git-svn-id: svn://cherokee-project.com/cherokee/trunk@1589 5dc97367-97f1-0310-9951-d761b3857238

diff --git a/cherokee/cherokee-panic b/cherokee/cherokee-panic
--- a/cherokee/cherokee-panic
+++ b/cherokee/cherokee-panic
@@ -1,13 +1,17 @@
 #!/bin/sh
 
-# Default action for Cherokee-Panic.
-# Possible actions are:
-#   mail - mail the error. You need a working MTA in the system.
-#   cat  - just print it
-if [ -x /usr/sbin/sendmail ]; then
-   action=mail
+# Actions for Cherokee-Panic:
+#   mail   - mail the error. You need a working MTA in the system.
+#   stdout - just print it
+#
+if test "x$CHEROKEE_PANIC_OUTPUT" != "x"; then
+    action="$CHEROKEE_PANIC_OUTPUT"
 else
-   action=cat
+    if [ -x /usr/sbin/sendmail ]; then
+	   action=mail
+    else
+	   action=stdout
+    fi
 fi
 
 # Redirect all output to our mail command
@@ -35,32 +39,32 @@ fi
 	    echo
 	fi
 
-	# Find out what binary we're debugging
-	if [ ! -d "/proc/$pid" ]; then
-		echo "$0: No such process: $pid"
-		exit 1
-	fi
-
 	if [ $os = "Linux" ]; then 
-	     BINARYNAME=`readlink "/proc/$pid/exe"`
+	    BINARYNAME=`readlink "/proc/$pid/exe"`
+	    known_os=yes
 	elif [ $os = "SunOS" ]; then
-	     BINARYNAME=`perl -e "print readlink(\"/proc/$pid/path/a.out\");"`
-     else
-	     echo "Unsupported OS: $os"
-	     exit 1
+	    BINARYNAME=`perl -e "print readlink(\"/proc/$pid/path/a.out\");"`
+	    known_os=yes
 	fi
 
 	# Generic header for the report
 	echo "The Cherokee 'panic action' script, $0,"
 	echo "was called for pid $pid ($BINARYNAME)."
 	echo
-
-	if [ -z "$BINARYNAME" ]; then
-		echo "This means there was a problem with the program, such as a segfault."
-		echo "However, the executable could not be found for process $pid."
-		echo "It may have died unexpectedly, or you may not have permission to"
-		echo "debug the process."
-		exit 1
+	
+     # Ensure /proc/$pid exists if it should
+	if test "x${known_os}" = "xyes"; then
+	    if [ ! -d "/proc/$pid" ]; then
+		   echo "$0: No such process: $pid"
+		   exit 1
+	    fi
+	    if test "x${BINARYNAME} " = "x"; then 
+		   echo "This means there was a problem with the program, such as a segfault."
+		   echo "However, the executable could not be found for process $pid."
+		   echo "It may have died unexpectedly, or you may not have permission to"
+		   echo "debug the process."
+		   exit 1
+	    fi
 	fi
 
 	# Check the debugger
@@ -91,14 +95,18 @@ fi
 
 	# Get the backtrace
 	if [ x$debugger = x$gdb ]; then 
-	     tmp_cmd=`mktemp -t` ||
+	     tmp_cmd=`mktemp -t 2>/dev/null` ||
 	     tmp_cmd=`mktemp "/tmp/chrk.XXXXXX"` || exit 1
 
 		( echo "print cherokee_version"
 		  echo "thread apply all bt full"
 		  echo "quit" ) >> $tmp_cmd
 
-		$gdb -x $tmp_cmd -batch "$BINARYNAME" "$pid"
+		if [ -z $BINARYNAME ]; then
+		    $gdb -x $tmp_cmd -batch --pid=$pid
+		else
+		    $gdb -x $tmp_cmd -batch "$BINARYNAME" "$pid"
+		fi
 		rm $tmp_cmd
 
 	elif [ x$debugger = x$dbx ]; then
@@ -110,7 +118,7 @@ fi
 	   mail)
 		  /usr/sbin/sendmail -t
 		  ;;
-	   cat)
+	   stdout)
 		  cat -
 		  ;;
 	   *)
